version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: miniopass
    tty: true
    volumes:
      - .:/app
    ports:
      - 5000:80
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
      MINIO_REGION_NAME: ap-northeast-1
    ports:
      - 9000:9000
      - 9001:9001
    command: ['server', '/data', '--console-address', ':9001']
    volumes:
      - s3-data:/data
volumes:
  s3-data: